export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#edeeef",
        "surface-tint": "#0053db",
        "secondary-fixed-dim": "#b4c5ff",
        primary: "#004ac6",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-surface": "#191c1d",
        "surface-container-low": "#f3f4f5",
        "on-primary-fixed": "#00174b",
        outline: "#737686",
        "on-surface-variant": "#434655",
        "secondary-container": "#acbfff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#31447b",
        "surface-variant": "#e1e3e4",
        error: "#ba1a1a",
        "surface-container-high": "#e7e8e9",
        "on-background": "#191c1d",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed": "#00174b",
        secondary: "#495c95",
        "on-tertiary-fixed-variant": "#7d2d00",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed-dim": "#ffb596",
        "on-error": "#ffffff",
        "primary-container": "#2563eb",
        "inverse-surface": "#2e3132",
        "error-container": "#ffdad6",
        "on-secondary-container": "#394c84",
        "surface-container-highest": "#e1e3e4",
        background: "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed": "#ffdbcd",
        surface: "#f8f9fa",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffede6",
        tertiary: "#943700",
        "inverse-primary": "#b4c5ff",
        "secondary-fixed": "#dbe1ff",
        "tertiary-container": "#bc4800",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-container": "#eeefff",
        "on-tertiary-fixed": "#360f00",
        soft: "#f1f5f9",
      },
    },
  },
  plugins: [],
};
